//! Docker Compose generator.
//!
//! Generates a docker-compose.yml with all infrastructure dependencies
//! detected from the routes (Kafka, PostgreSQL, Redis, etc.).
//! Developer just runs `docker-compose up -d` and everything works.

use std::path::Path;

use crate::ast::camel_ir::{CamelProject, RouteEndpoint, RouteStep};
use crate::Result;

pub fn generate(ir: &CamelProject, output_dir: &Path) -> Result<()> {
    let mut services = Vec::new();
    let mut needs_kafka = false;
    let mut needs_postgres = false;
    let mut needs_activemq = false;
    let mut needs_redis = false;
    let mut needs_sftp = false;

    // Scan all routes for dependencies
    for route in &ir.routes {
        scan_endpoint(
            &route.source,
            &mut needs_kafka,
            &mut needs_postgres,
            &mut needs_activemq,
            &mut needs_redis,
            &mut needs_sftp,
        );
        for step in &route.steps {
            if let RouteStep::ToUri(ref uri) = step {
                let ep = RouteEndpoint::Uri(uri.clone());
                scan_endpoint(
                    &ep,
                    &mut needs_kafka,
                    &mut needs_postgres,
                    &mut needs_activemq,
                    &mut needs_redis,
                    &mut needs_sftp,
                );
            }
        }
    }

    // Build services
    services.push(format!(
        r#"  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:{deps}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5"#,
        deps = if needs_kafka || needs_postgres || needs_activemq {
            let mut d = String::from("\n");
            if needs_postgres {
                d.push_str("      - postgres\n");
            }
            if needs_kafka {
                d.push_str("      - kafka\n");
            }
            if needs_activemq {
                d.push_str("      - activemq\n");
            }
            d
        } else {
            " []".into()
        }
    ));

    if needs_postgres {
        services.push(
            r#"  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5"#
                .into(),
        );
    }

    if needs_kafka {
        services.push(
            r#"  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5"#
                .into(),
        );
    }

    if needs_activemq {
        services.push(
            r#"  activemq:
    image: apache/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5"#
                .into(),
        );
    }

    if needs_redis {
        services.push(
            r#"  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5"#
                .into(),
        );
    }

    if needs_sftp {
        services.push(
            r#"  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "2222:22"
    command: user:password:::upload"#
                .into(),
        );
    }

    // Assemble
    let mut yaml = String::new();
    yaml.push_str("# Docker Compose for local development\n");
    yaml.push_str("# Generated by MuleForge — run: docker-compose up -d\n\n");
    yaml.push_str("services:\n");
    for svc in &services {
        yaml.push_str(svc);
        yaml.push('\n');
        yaml.push('\n');
    }

    // Volumes
    if needs_postgres {
        yaml.push_str("volumes:\n  pgdata:\n");
    }

    std::fs::write(output_dir.join("docker-compose.yml"), yaml)?;
    Ok(())
}

fn scan_endpoint(
    ep: &RouteEndpoint,
    kafka: &mut bool,
    pg: &mut bool,
    amq: &mut bool,
    redis: &mut bool,
    sftp: &mut bool,
) {
    if let RouteEndpoint::Uri(ref uri) = ep {
        if uri.starts_with("kafka:") {
            *kafka = true;
        }
        if uri.contains("sql:") || uri.contains("jdbc:") {
            *pg = true;
        }
        if uri.starts_with("jms:") || uri.starts_with("amqp:") {
            *amq = true;
        }
        if uri.contains("redis:") || uri.contains("infinispan:") {
            *redis = true;
        }
        if uri.starts_with("sftp:") {
            *sftp = true;
        }
    }
}
