//! Kong emitter: generates decK declarative config for Kong Gateway.

use std::path::Path;

use crate::ast::camel_ir::{CamelProject, RouteEndpoint};
use crate::Result;

pub fn emit(ir: &CamelProject, output_dir: &Path) -> Result<()> {
    let kong_dir = output_dir.join("kong");
    std::fs::create_dir_all(&kong_dir)?;

    let mut yaml = String::new();
    yaml.push_str("# Kong declarative configuration (decK format)\n");
    yaml.push_str("# Generated by MuleForge\n");
    yaml.push_str("_format_version: \"3.0\"\n\n");
    yaml.push_str("services:\n");

    let svc_name = &ir.name;
    yaml.push_str(&format!("  - name: {}\n", svc_name));
    yaml.push_str(&format!("    url: http://{}:8080\n", svc_name));
    yaml.push_str("    routes:\n");

    for route in &ir.routes {
        if let RouteEndpoint::Uri(ref uri) = route.source {
            if uri.starts_with("platform-http:") {
                let path = uri
                    .strip_prefix("platform-http:")
                    .unwrap_or("/")
                    .split('?')
                    .next()
                    .unwrap_or("/");
                let methods = uri
                    .split("httpMethodRestrict=")
                    .nth(1)
                    .map(|m| m.split('&').next().unwrap_or("GET"))
                    .unwrap_or("GET");

                yaml.push_str(&format!("      - name: {}-route\n", route.id));
                yaml.push_str("        paths:\n");
                yaml.push_str(&format!("          - {}\n", path));
                yaml.push_str("        methods:\n");
                for m in methods.split(',') {
                    yaml.push_str(&format!("          - {}\n", m.trim()));
                }
                yaml.push_str("        strip_path: false\n");
            }
        }
    }

    yaml.push_str("    plugins:\n");
    yaml.push_str("      - name: rate-limiting\n");
    yaml.push_str("        config:\n");
    yaml.push_str("          minute: 100\n");
    yaml.push_str("          policy: local\n");
    yaml.push_str("      - name: cors\n");
    yaml.push_str("        config:\n");
    yaml.push_str("          origins:\n");
    yaml.push_str("            - \"*\"\n");
    yaml.push_str("          methods:\n");
    yaml.push_str("            - GET\n");
    yaml.push_str("            - POST\n");
    yaml.push_str("            - PUT\n");
    yaml.push_str("            - DELETE\n");

    std::fs::write(kong_dir.join("kong.yaml"), yaml)?;
    Ok(())
}
