//! Config emitter: generates application.properties from Camel IR.

use std::path::Path;

use crate::ast::camel_ir::CamelProject;
use crate::Result;

pub fn emit(ir: &CamelProject, output_dir: &Path) -> Result<()> {
    let resources_dir = output_dir.join("src/main/resources");
    std::fs::create_dir_all(&resources_dir)?;

    let mut props = String::new();
    props.push_str("# Generated by MuleForge\n");
    props.push_str("# Quarkus + Camel configuration\n\n");

    // Core Quarkus properties
    props.push_str("# HTTP\n");
    props.push_str("quarkus.http.port=8080\n");
    props.push_str(&format!("quarkus.application.name={}\n\n", ir.name));

    // Health
    props.push_str("# Health checks\n");
    props.push_str("quarkus.health.extensions.enabled=true\n\n");

    // Camel properties
    props.push_str("# Camel\n");
    props.push_str("camel.context.name=muleforge-migrated\n\n");

    // User-defined properties (from Mule application.properties)
    if !ir.quarkus_properties.is_empty() {
        props.push_str("# Migrated from Mule application properties\n");
        let mut sorted: Vec<_> = ir.quarkus_properties.iter().collect();
        sorted.sort_by_key(|(k, _)| k.as_str());
        for (k, v) in sorted {
            props.push_str(&format!("{}={}\n", k, v));
        }
        props.push('\n');
    }

    // Detect needed component configs from routes
    let route_uris: Vec<String> = ir
        .routes
        .iter()
        .map(|r| match &r.source {
            crate::ast::camel_ir::RouteEndpoint::Uri(u) => u.clone(),
            crate::ast::camel_ir::RouteEndpoint::Direct(d) => format!("direct:{}", d),
        })
        .collect();

    if route_uris.iter().any(|u| u.starts_with("kafka:")) {
        props.push_str("# Kafka\n");
        props.push_str("camel.component.kafka.brokers=${KAFKA_BROKERS:localhost:9092}\n");
        props.push_str("camel.component.kafka.group-id=${KAFKA_GROUP_ID:muleforge-group}\n\n");
    }

    if route_uris.iter().any(|u| u.starts_with("jms:")) {
        props.push_str("# JMS\n");
        props.push_str("quarkus.artemis.url=${JMS_BROKER_URL:tcp://localhost:61616}\n");
        props.push_str("quarkus.artemis.username=${JMS_USERNAME:admin}\n");
        props.push_str("quarkus.artemis.password=${JMS_PASSWORD:admin}\n\n");
    }

    if route_uris
        .iter()
        .any(|u| u.contains("sql:") || u.contains("jdbc:"))
    {
        props.push_str("# Database\n");
        props.push_str("quarkus.datasource.db-kind=postgresql\n");
        props.push_str(
            "quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/app}\n",
        );
        props.push_str("quarkus.datasource.username=${DB_USERNAME:postgres}\n");
        props.push_str("quarkus.datasource.password=${DB_PASSWORD:postgres}\n\n");
    }

    std::fs::write(resources_dir.join("application.properties"), props)?;

    // Production overlay
    let mut prod = String::new();
    prod.push_str("# Production overrides\n");
    prod.push_str("%prod.quarkus.log.level=INFO\n");
    prod.push_str("%prod.quarkus.http.port=8080\n");
    std::fs::write(resources_dir.join("application.prod.properties"), prod)?;

    Ok(())
}
